version: '3'

services:
  ace-app:
    image: taaphise/art-currency-exchange:$DOCKER_TAG  # Replace with your image tag
    ports:
      - "80:80"  # Expose port 80 for local testing (optional)
    environment:
      - NODE_ENV=production  # Set the environment to production
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Optional: You can add your Nginx config here
    networks:
      - ace-network  # Optional: Defines a network for container communication

# Define custom networks if needed
networks:
  ace-network:
    driver: bridge