name: Deploy to Cloud Server

on:
  push:
    branches:
      - main  # Trigger the action on pushes to the main branch
  pull_request:
    branches:
      - main  # Optional: Trigger on PRs to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout Code
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx (optional but recommended for multi-platform builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Step 3: Build Docker image and push to Docker Hub or a Container Registry
    - name: Build and Push Docker Image
      run: |
        docker build -t taaphise/art-currency-exchange:$GITHUB_SHA .
        docker push taaphise/art-currency-exchange:$GITHUB_SHA

    # Step 4: Docker Hub login
    - name: Docker Hub Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 5: Set up SSH to deploy to cloud server
    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Step 6: Deploy to Cloud Server
    - name: Deploy to Cloud Server
      run: |
        ssh -o StrictHostKeyChecking=no root@45.77.154.244 << 'EOF'
          # Ensure Docker and Docker Compose are installed
          docker --version
          docker-compose --version

          # Go to the directory where the docker-compose.yml file is located
          cd /path/to/your/project  # Replace with the correct path on your server

          # Pull the newly built image
          docker pull taaphise/art-currency-exchange:$GITHUB_SHA

          # Ensure docker-compose.yml file is present
          ls -l docker-compose.yml  # Verify that the file exists

          # Deploy using Docker Compose
          docker-compose down
          docker-compose up -d
        EOF