name: Deploy to Cloud Server

on:
  push:
    branches:
      - main  # Trigger the action on pushes to the main branch
  pull_request:
    branches:
      - main  # Optional: Trigger on PRs to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx (optional but recommended for multi-platform builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username stored in GitHub Secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password stored in GitHub Secrets

    # Step 4: Build Docker image and push to Docker Hub
    - name: Build and Push Docker Image
      run: |
        docker build -t taaphise/art-currency-exchange:$GITHUB_SHA .
        docker push taaphise/art-currency-exchange:$GITHUB_SHA

    # Step 5: Set up SSH to deploy to the cloud server
    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Step 6: SSH into the server and deploy
    - name: Deploy to Cloud Server
      run: |
        ssh -o StrictHostKeyChecking=no root@[2001:19f0:0:70d6:5400:5ff:fe5c:582a] << 'EOF'
          # Pull the latest Docker image from Docker Hub
          docker pull taaphise/art-currency-exchange:$GITHUB_SHA
          
          # Stop the currently running containers (if any)
          docker-compose down
          
          # Start the containers with the latest image
          docker-compose up -d
        EOF